[package]
name = "mexe"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"
float-cmp = "0.9"

[[bench]]
name = "benchmarks"
harness = false
